# Generated by Django 2.2.9 on 2020-02-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_resourcebase_bbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcebase',
            old_name='bbox',
            new_name='bbox_polygon',
        ),
    ]
